name: test run for 6 models (SA)

on:
  # schedule:
    # - cron: '0 02 * * 6' # e.g. --> cron: '0 20 * * *' (means runs at 4am daily at GMT+08, Singapore time)
  workflow_dispatch: # Create a button to trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu-latest # windows-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # install the python version needed (3.9)
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        # env:
        #   GOOGLEAPI: ${{secrets.GOOGLEAPI}}
        run: python main1.py

      - name: pull changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated files" --allow-empty)

      - name: push changes
        run: |
            git push origin main
